In [33]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

X = np.load("X.npy")
y = np.load("y.npy")

In [34]:
print(X.shape)
print(y.shape)

print(X)

(1246, 10, 1)
(1246,)
[[[2.35523287e-02]
  [3.26507460e-02]
  [2.79863795e-02]
  ...
  [1.09420255e-03]
  [3.97346453e-03]
  [7.54367360e-03]]

 [[3.26507460e-02]
  [2.79863795e-02]
  [3.62790077e-03]
  ...
  [3.97346453e-03]
  [7.54367360e-03]
  [8.58022957e-03]]

 [[2.79863795e-02]
  [3.62790077e-03]
  [5.18323089e-04]
  ...
  [7.54367360e-03]
  [8.58022957e-03]
  [0.00000000e+00]]

 ...

 [[9.30871370e-01]
  [9.23303700e-01]
  [8.71453168e-01]
  ...
  [8.31722853e-01]
  [8.46030573e-01]
  [8.51647100e-01]]

 [[9.23303700e-01]
  [8.71453168e-01]
  [8.74645832e-01]
  ...
  [8.46030573e-01]
  [8.51647100e-01]
  [8.51528920e-01]]

 [[8.71453168e-01]
  [8.74645832e-01]
  [8.68910944e-01]
  ...
  [8.51647100e-01]
  [8.51528920e-01]
  [8.21672049e-01]]]


In [ ]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)
y = y.view(-1, 1)

X = X.squeeze()

In [36]:
class StockPredictor(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(10, 32)
        self.layer2 = nn.Linear(32, 16)
        self.layer3 = nn.Linear(16, 1)

        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.layer1(x)

        x = self.relu(x)

        x = self.layer2(x)
        x = self.relu(x)

        x = self.layer3(x)
        return x

model = StockPredictor()

In [37]:
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

for epoch in range(100):
    predictions = model(X)

    loss = criterion(predictions, y)

    optimizer.zero_grad()

    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())
    
    
    


Epoch: 0 Loss: 0.16734708845615387
Epoch: 10 Loss: 0.10815345495939255
Epoch: 20 Loss: 0.07668799161911011
Epoch: 30 Loss: 0.06776808202266693
Epoch: 40 Loss: 0.06693574041128159
Epoch: 50 Loss: 0.06452436000108719
Epoch: 60 Loss: 0.06320806592702866
Epoch: 70 Loss: 0.06249585002660751
Epoch: 80 Loss: 0.06192084029316902
Epoch: 90 Loss: 0.06144973263144493
